export const AQUABLUE = {};

/**
 * The set of Ability Scores used within the sytem.
 * @type {Object}
 */
 AQUABLUE.maîtrises = {
    "physique": "AQUABLUE.MAÎTRISE.PHYSIQUE.Nom",
    "mental": "AQUABLUE.MAÎTRISE.MENTAL.Nom",
    "social": "AQUABLUE.MAÎTRISE.SOCIAL.Nom",
 };

 AQUABLUE.categories = {
    "aventure": "AQUABLUE.MAÎTRISE.PHYSIQUE.CATEGORIE.AVENTURE.Nom",
    "combat": "AQUABLUE.MAÎTRISE.PHYSIQUE.CATEGORIE.COMBAT.Nom",
    "savoirFaire": "AQUABLUE.MAÎTRISE.PHYSIQUE.CATEGORIE.SAVOIRFAIRE.Nom",
    "sagesse": "AQUABLUE.MAÎTRISE.MENTAL.CATEGORIE.SAGESSE.Nom",
    "technique": "AQUABLUE.MAÎTRISE.MENTAL.CATEGORIE.TECHNIQUE.Nom",
    "volonte": "AQUABLUE.MAÎTRISE.MENTAL.CATEGORIE.VOLONTE.Nom",
    "ame": "AQUABLUE.MAÎTRISE.SOCIAL.CATEGORIE.ÂME.Nom",
    "art": "AQUABLUE.MAÎTRISE.SOCIAL.CATEGORIE.ART.Nom",
    "charisme": "AQUABLUE.MAÎTRISE.SOCIAL.CATEGORIE.CHARISME.Nom",
 };

 AQUABLUE.competences = {
    "athletisme": "AQUABLUE.MAÎTRISE.PHYSIQUE.CATEGORIE.AVENTURE.COMPETENCE.Athletisme",
    "plongee": "AQUABLUE.MAÎTRISE.PHYSIQUE.CATEGORIE.AVENTURE.COMPETENCE.Plongee",
    "survie": "AQUABLUE.MAÎTRISE.PHYSIQUE.CATEGORIE.AVENTURE.COMPETENCE.Survie",
    "armeDistance": "AQUABLUE.MAÎTRISE.PHYSIQUE.CATEGORIE.COMBAT.COMPETENCE.ArmeDistance",
    "combatSubaquatique": "AQUABLUE.MAÎTRISE.PHYSIQUE.CATEGORIE.COMBAT.COMPETENCE.CombatSubaquatique",
    "corpsACorps": "AQUABLUE.MAÎTRISE.PHYSIQUE.CATEGORIE.COMBAT.COMPETENCE.CorpsACorps",
    "artisanat": "AQUABLUE.MAÎTRISE.PHYSIQUE.CATEGORIE.SAVOIRFAIRE.COMPETENCE.Artisanat",
    "chassePeche": "AQUABLUE.MAÎTRISE.PHYSIQUE.CATEGORIE.SAVOIRFAIRE.COMPETENCE.ChassePeche",
    "prodigeTerre": "AQUABLUE.MAÎTRISE.PHYSIQUE.CATEGORIE.SAVOIRFAIRE.COMPETENCE.ProdigeTerre",
    "erudition": "AQUABLUE.MAÎTRISE.MENTAL.CATEGORIE.SAGESSE.COMPETENCE.Erudition",
    "medecine": "AQUABLUE.MAÎTRISE.MENTAL.CATEGORIE.SAGESSE.COMPETENCE.Medecine",
    "prodigeAir": "AQUABLUE.MAÎTRISE.MENTAL.CATEGORIE.SAGESSE.COMPETENCE.ProdigeAir",
    "astres": "AQUABLUE.MAÎTRISE.MENTAL.CATEGORIE.TECHNIQUE.COMPETENCE.Astres",
    "pilotage": "AQUABLUE.MAÎTRISE.MENTAL.CATEGORIE.TECHNIQUE.COMPETENCE.Pilotage",
    "technologie": "AQUABLUE.MAÎTRISE.MENTAL.CATEGORIE.TECHNIQUE.COMPETENCE.Technologie",
    "discussion": "AQUABLUE.MAÎTRISE.MENTAL.CATEGORIE.VOLONTE.COMPETENCE.Discussion",
    "investigation": "AQUABLUE.MAÎTRISE.MENTAL.CATEGORIE.VOLONTE.COMPETENCE.Investigation",
    "meditation": "AQUABLUE.MAÎTRISE.MENTAL.CATEGORIE.VOLONTE.COMPETENCE.Meditation",
    "chamanisme": "AQUABLUE.MAÎTRISE.SOCIAL.CATEGORIE.ÂME.COMPETENCE.Chamanisme",
    "contacts": "AQUABLUE.MAÎTRISE.SOCIAL.CATEGORIE.ÂME.COMPETENCE.Contacts",
    "empathie": "AQUABLUE.MAÎTRISE.SOCIAL.CATEGORIE.ÂME.COMPETENCE.Empathie",
    "larcin": "AQUABLUE.MAÎTRISE.SOCIAL.CATEGORIE.ART.COMPETENCE.Larcin",
    "performance": "AQUABLUE.MAÎTRISE.SOCIAL.CATEGORIE.ART.COMPETENCE.Performance",
    "prodigeEau": "AQUABLUE.MAÎTRISE.SOCIAL.CATEGORIE.ART.COMPETENCE.ProdigeEau",
    "commandement": "AQUABLUE.MAÎTRISE.SOCIAL.CATEGORIE.CHARISME.COMPETENCE.Commandement",
    "dressage": "AQUABLUE.MAÎTRISE.SOCIAL.CATEGORIE.CHARISME.COMPETENCE.Dressage",
    "seduction": "AQUABLUE.MAÎTRISE.SOCIAL.CATEGORIE.CHARISME.COMPETENCE.Seduction",
 };